development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: jobs
  pool: 5
  username: root
  password:
  host: localhost
  variables:
    sql_mode: TRADITIONAL

test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: jobs_test
  pool: 5
  username: root
  password:
  host: localhost
  variables:
    sql_mode: TRADITIONAL
